apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  description: Staging environment
  sourceRepos:
    - 'https://github.com/myorg/gitops-pipeline-template'
  destinations:
    - namespace: staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
    - group: 'apps'
      kind: 'Deployment'
    - group: ''
      kind: 'Service'
    - group: 'networking.k8s.io'
      kind: 'Ingress'
  orphanedResources:
    warn: true
